#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.

hassan=0

while [ $hassan -lt 10 ]
do
  if [ $hassan -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( hassan++ ))
done
