#!/usr/bin/env bash
# Displays numbers from 1 to 20

hassan=1

while [ $hassan -le 20 ]
do
	echo "$hassan"
	case $hassan in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( hassan++ ))
done
